[build]
publish = "build/web"
command = "flutter build web"

[build.environment]
FLUTTER_VERSION = "3.35.6"

[build.lifecycle]
postInstall = "wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz && tar xf flutter_linux_${FLUTTER_VERSION}-stable.tar.xz"
